---
# content_views.yml
# these are our default SOE Content View definitions for our standard base Satellite build
description: "Published by ansible-tower on {{ ansible_date_time.date }}"
filter_enddate: "{{ ansible_date_time.date }}"
num_cvs_to_keep: 3
force_publish: true
content_views:
  - name: "RHEL8_SOE"
    desc: "Red Hat Enterprise Linux 8 Standard Operating Environment Content"
    org: "{{ sat_organization }}"
    repositories:
    - name: "Red Hat Satellite Tools 6.10 for RHEL 7 for ARM RPMs aarch64 7Server"
      product: "Red Hat Enterprise Linux for ARM 64"
    - name: Red Hat Ansible Engine 2.9 for RHEL 8 x86_64 RPMs
      product: Red Hat Ansible Engine
    filters:
    - name: "AllPackagesNoErrata"
      type: "rpm"
      inclusion: "true"
      description: "Include all packages with no errata for all repositories"
      original_packages: true
      repositories: "[]"
    - name: "ErrataByDate"
      type: "erratum"
      inclusion: "true"
      description: "Include all errata updated as of {{ filter_enddate }}"
      repositories: "[]"
      rules:
      - name: "errata-by-date-{{ filter_enddate }}"
        end_date: "{{ filter_enddate }}"
        date_type: "updated"
        types:
        - "enhancement"
        - "bugfix"
        - "security"
    - name: "NoFireFox"
      type: "rpm"
      inclusion: "false"
      description: "Do not provide Firefox to servers"
      original_packages: true
      repositories: "[]"
      rules:
      - name: "firefox*"
        basearch: "x86_64"
    date_filter_name: "ErrataByDate"
    environments:
    - "Library"

  - name: "RHEL8_SOE"
    desc: "RHEL 9 CV"
    org: "{{ sat_organization }}"
    repositories:
    - name: "Red Hat Enterprise Linux 9 for ARM 64 - AppStream RPMs 9"
      product: "Red Hat Enterprise Linux for ARM 64"
    - name: "Red Hat Enterprise Linux 9 for ARM 64 - BaseOS RPMs 9"
      product: "Red Hat Enterprise Linux for ARM 64"
    filters:
    - name: "AllPackagesNoErrata"
      type: "rpm"
      inclusion: "true"
      description: "Include all packages with no errata for all repositories"
      original_packages: true
      repositories: "[]"
    - name: "ErrataByDate"
      type: "erratum"
      inclusion: "true"
      description: "Include all errata updated as of {{ filter_enddate }}"
      repositories: "[]"
      rules:
      - name: "errata-by-date-{{ filter_enddate }}"
        end_date: "{{ filter_enddate }}"
        date_type: "updated"
        types:
        - "enhancement"
        - "bugfix"
        - "security"
    - name: "NoFireFox"
      type: "rpm"
      inclusion: "false"
      description: "Do not provide Firefox to servers"
      original_packages: true
      repositories: "[]"
      rules:
      - name: "firefox*"
        basearch: "x86_64"
    date_filter_name: "ErrataByDate"
    environments:
    - "Library"
