---
# A valid mac is required when using bare metal as compute resource
# this can come from a query of satellites available discovered hosts or
# be a known value - for all other compute resources, the mac is assigned by
# the compute resource
discovered_hosts_resouce: "discovered_hosts"
discovered_hosts_search: "disk_count = 1 and memory > 32000"
discovered_host_req_nic_count: 1  #we use > below so does not include lo 
host_build_comment: "Created by ansible for content test"
debugger: false
deploy: true

# NOTE: Baremetal requires a valid MAC for a discovered host
# Supplying one here will specify a particular discovered host
# providing "ff:ff:ff:ff:ff:ff" will use search criteria
hostlist:
  - fqdn: "us-east-2.compute.internal"
    hostgroup: "dev-hg"
    kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9"
    compute_resource: "aws"
    compute_profile: "2-Medium"
    mac: "00:50:56:ff:ff:ff"
    dhostname: ""
  
